### PR TITLE
feat:support hostNetWork for components

### PR DESCRIPTION
**Pull request by qchenzi**

### CODE REVIEW

**Comment by haorenfsa** [comment]
Hi @qchenzi, the patch looks good. Still there're 3 things to do, before we could merge it.
1. [ ] Generate updates for CRD by Using `make  generate-all` command under the root of the repo.
2. [ ] Add an integration test for this new feature by adding the new fields in https://github.com/zilliztech/milvus-operator/blob/main/test/min-mc-feature.yaml, so that our CI can test if it works.
3. [ ] Sign off all your commits https://github.com/zilliztech/milvus-operator/pull/141/checks?check_run_id=26704300058

**Comment by qchenzi** [comment]
> Hi @qchenzi, the patch looks good. Still there're 3 things to do, before we could merge it.
> 
> 1. [ ]  Generate updates for CRD by Using `make  generate-all` command under the root of the repo.
> 2. [ ]  Add an integration test for this new feature by adding the new fields in https://github.com/zilliztech/milvus-operator/blob/main/test/min-mc-feature.yaml, so that our CI can test if it works.
> 3. [ ]  Sign off all your commits https://github.com/zilliztech/milvus-operator/pull/141/checks?check_run_id=26704300058

Hi @haorenfsa,

Thank you for your feedback. I have completed the three tasks you mentioned:

1. Updated the CRDs using **make generate-all**, and you can find it [deploy/manifests/deployment.yaml](https://github.com/qchenzi/milvus-operator/commit/c62f5f2013a2297be5e668f3a5f707633b8e9c03#diff-2002e0172d51f36e9a257d038fe7d88d3f006201f13e9877e189dc7e2963843a)

2. Added an integration test for the new feature, and you can find it [test/min-mc-feature.yaml](https://github.com/qchenzi/milvus-operator/commit/c62f5f2013a2297be5e668f3a5f707633b8e9c03#diff-6c8a904fcdebf6e205d6a7f568399d24a1fd7871b615980a0a2913e565b9d9c1)

3. Rebased and squashed all my commits into one.

Please let me know if there is anything else required.

Best regards.

**Comment by haorenfsa** [comment]
Hi @qchenzi, you commits still not signed off, use `git commit --amend -s` to sign off existed commit, and then push force again.

**Comment by qchenzi** [comment]
Hi @haorenfsa,

Thank you for pointing that out. I have correctly signed off all my commits as per your instructions. Please review.

**Comment by haorenfsa** [comment]
@qchenzi Oh, the new feature test seems to be failing. It's because that the CRD should not only be updated in [deploy/manifests/deployment.yaml](https://github.com/qchenzi/milvus-operator/commit/c62f5f2013a2297be5e668f3a5f707633b8e9c03#diff-2002e0172d51f36e9a257d038fe7d88d3f006201f13e9877e189dc7e2963843a) but also in https://github.com/zilliztech/milvus-operator/tree/main/config/crd/bases and https://github.com/zilliztech/milvus-operator/blob/main/charts/milvus-operator/templates/crds.yaml.

**Comment by haorenfsa** [comment]
The `make generate-all` should be able to update them all, plz check if you miss them when you commit the patch.

**Comment by qchenzi** [comment]
Hi @haorenfsa 

Thank you for pointing out the missing updates. I have reviewed the files and realized that I indeed missed updating some files. 

I have now run make generate-all again to ensure all necessary files are updated and have committed these changes. Please review the latest updates.

Thank you for your patience and assistance.

**Comment by haorenfsa** [comment]
Thank you @qchenzi!  
The new feature test now failed because port 9091 is used for all milvus pods to export metrics, when milvus pods are scheduled to the same node, it conflicts. Last feature is related to hpa. Thus in test we have more than 1 proxy pods, and they are scheduled to the same node. I checked the logs, other pods are working well. Thus I think it's ok to merge. 
Thank you again for providing this patch!

**Pull request merged**
